/**
 * 🛠 Utility Helpers & Factory Functions
 */

/**
 * 🚀 Event Object Factory
 * 모든 이벤트(메모, 크롤링 데이터 등)의 형식을 통일합니다.
 */
export function createEventObject({
    id,
    title,
    summary,
    tags = [],
    lat,
    lng,
    imageUrl,
    region = "Global",
    country = "Unknown"
}) {
    // ID가 없으면 자동 생성
    const finalId = id || `kuzmo-${Date.now()}-${Math.random().toString(36).substr(2, 5)}`;
    
    // 기본 이미지 처리
    const finalImageUrl = imageUrl || `https://picsum.photos/seed/${encodeURIComponent(title + lat + lng)}/400/300`;

    // 국가 자동 판별 고도화 (v11.6)
    let finalCountry = country;
    if (country === "Unknown") {
        const japanKeywords = ["일본", "Japan", "도쿄", "오사카", "교토", "후쿠오카", "삿포로", "오키나와", "나고야", "요코하마", "하코네", "나라", "고베", "히로시마"];
        if (tags.some(t => japanKeywords.some(kw => t.includes(kw)))) {
            finalCountry = "Japan";
        } else {
            finalCountry = "Korea";
        }
    }

    // 마커 타입 결정 (분류 기준 생성 시 확정)
    let markerType = 'unknown';
    if (finalId.startsWith('s-db-')) markerType = 'tourist';
    else if (finalId.startsWith('kuzmo-')) markerType = 'memory';

    return {
        id: finalId,
        title: title || "이름 없는 장소",
        summary: summary || "내용 없음",
        tags: Array.isArray(tags) ? tags : [],
        lat: parseFloat(lat),
        lng: parseFloat(lng),
        imageUrl: finalImageUrl,
        region,
        country: finalCountry,
        timestamp: Date.now(),
        type: markerType
    };
}

/**
 * 📝 Convert Event Object to Markdown String
 */
export function eventToMarkdown(ev) {
    if (!ev) return "";
    const date = new Date(ev.timestamp || Date.now()).toLocaleString('ko-KR');

    // 🚀 [AI-OPTIMIZED] Clean and standardized markdown without enclosure
    return `---
title: ${ev.title}
date: ${date}
region: ${ev.region || 'Global'}
tags: ${ev.tags?.join(', ')}
lat: ${ev.lat}
lng: ${ev.lng}
imageUrl: ${ev.imageUrl}
---

# ${ev.title}

${ev.content || ev.summary || ev.description || "내용 없음"}

---
*Generated by Kuzmo Intelligent Map Engine - Node ID: ${ev.id}*
`.trim();
}

/**
 * 📍 Jittering (좌표 미세 분산)
 */
export function applyJitter(lat, lng, amount = 0.015) {
    return {
        lat: lat + (Math.random() - 0.5) * amount,
        lng: lng + (Math.random() - 0.5) * amount
    };
}
/**
 * 📍 Geodesic Distance (Haversine Formula) - Unit: KM
 */
export function calculateDistance(lat1, lon1, lat2, lon2) {
    const R = 6371; // Earth Radius in km
    const dLat = (lat2 - lat1) * Math.PI / 180;
    const dLon = (lon2 - lon1) * Math.PI / 180;
    const a = 
        Math.sin(dLat/2) * Math.sin(dLat/2) +
        Math.cos(lat1 * Math.PI / 180) * Math.cos(lat2 * Math.PI / 180) * 
        Math.sin(dLon/2) * Math.sin(dLon/2);
    const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));
    return R * c;
}

/**
 * 📂 [SYNC-BRIDGE] Sync Selected Items to Local Filesystem via C# (v1.0)
 * 브라우저 샌드박스를 넘어 실제 로컬 파일을 동기화하고 탐색기를 엽니다.
 */
export async function syncToLocalFilesystem(selectedItems) {
    if (!selectedItems || selectedItems.length === 0) return;

    // C# 서버가 이해할 수 있는 본문 리스트로 변환
    const payload = selectedItems.map(ev => ({
        title: ev.title,
        content: eventToMarkdown(ev)
    }));

    try {
        const response = await fetch('http://localhost:9091/api/sync/local-export', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(payload)
        });
        
        if (response.ok) {
            const result = await response.json();
            console.log("🚀 [KUZMO_SYNC] Local Files Synchronized:", result);
            return result;
        }
    } catch (err) {
        console.error("❌ [KUZMO_SYNC_FAILED] C# Bridge unreachable:", err);
    }
    return null;
}
